BEGIN;
INSERT INTO poses VALUES(1,'?','','','unknown',NULL,NULL);
INSERT INTO poses VALUES(29,'a0','a','',NULL,'aj0 or av0',NULL);
INSERT INTO poses VALUES(30,'a1','a','','comparative (-er)','aj1 or av1',NULL);
INSERT INTO poses VALUES(31,'a2','a','','superlative (-est)','aj2 or av2',NULL);
INSERT INTO poses VALUES(42,'abbr','abbr','special','abbreviation',NULL,NULL);
INSERT INTO poses VALUES(23,'aj0','aj','',NULL,NULL,NULL);
INSERT INTO poses VALUES(24,'aj1','aj','','comparative (-er)',NULL,NULL);
INSERT INTO poses VALUES(25,'aj2','aj','','superlative (-est)',NULL,NULL);
INSERT INTO poses VALUES(26,'av0','av','',NULL,NULL,NULL);
INSERT INTO poses VALUES(27,'av1','av','','comparative (-er)',NULL,NULL);
INSERT INTO poses VALUES(28,'av2','av','','superlative (-est)',NULL,NULL);
INSERT INTO poses VALUES(2,'c','c','','conjunction',NULL,NULL);
INSERT INTO poses VALUES(4,'d','d','','determiner',NULL,NULL);
INSERT INTO poses VALUES(40,'d1','d','','comparative',NULL,NULL);
INSERT INTO poses VALUES(41,'d2','d','','superlative',NULL,NULL);
INSERT INTO poses VALUES(39,'ds','d','','plural',NULL,NULL);
INSERT INTO poses VALUES(5,'i','i','','interjection',NULL,NULL);
INSERT INTO poses VALUES(21,'m0','m','',NULL,'n0 or v0',NULL);
INSERT INTO poses VALUES(22,'ms','m','','(-s)','ns or vs',NULL);
INSERT INTO poses VALUES(6,'n0','n','',NULL,NULL,NULL);
INSERT INTO poses VALUES(9,'np','n','','possessive',NULL,NULL);
INSERT INTO poses VALUES(7,'ns','n','','plural',NULL,NULL);
INSERT INTO poses VALUES(10,'nsp','n','','plural possessive',NULL,NULL);
INSERT INTO poses VALUES(8,'nss','n','','plural of plural',NULL,NULL);
INSERT INTO poses VALUES(11,'nssp','n','','plural of plural possessive',NULL,NULL);
INSERT INTO poses VALUES(32,'pn0','pn','',NULL,NULL,NULL);
INSERT INTO poses VALUES(33,'pn1','pn','','objective (you/him/her/...)',NULL,NULL);
INSERT INTO poses VALUES(35,'pnd','pn','','determiner (your/his/her/...)',NULL,NULL);
INSERT INTO poses VALUES(36,'pnp','pn','','possessive (yours/his/hers/...)',NULL,NULL);
INSERT INTO poses VALUES(37,'pnr0','pn','','reflexive singular (yourself/...)',NULL,NULL);
INSERT INTO poses VALUES(38,'pnrs','pn','','reflexive plural (yourselves/...)',NULL,NULL);
INSERT INTO poses VALUES(34,'pns','pn','','plural',NULL,NULL);
INSERT INTO poses VALUES(3,'pp','pp','','preposition',NULL,NULL);
INSERT INTO poses VALUES(44,'pre','pre','nonword','prefix',NULL,NULL);
INSERT INTO poses VALUES(43,'s','s','special','contraction',NULL,NULL);
INSERT INTO poses VALUES(45,'suf','suf','nonword','suffix',NULL,NULL);
INSERT INTO poses VALUES(12,'v0','v','',NULL,NULL,NULL);
INSERT INTO poses VALUES(13,'vd','v','','past tense (-ed)',NULL,NULL);
INSERT INTO poses VALUES(14,'vd2','v','','past tense plural (were)',NULL,NULL);
INSERT INTO poses VALUES(16,'vg','v','','present participle (-ing)',NULL,NULL);
INSERT INTO poses VALUES(15,'vn','v','','past participle (-en)',NULL,NULL);
INSERT INTO poses VALUES(17,'vs','v','','present tense (-s)',NULL,NULL);
INSERT INTO poses VALUES(18,'vs2','v','','present tense second-person singular (are)',NULL,NULL);
INSERT INTO poses VALUES(19,'vs3','v','','present tense third-person singular (is)',NULL,NULL);
INSERT INTO poses VALUES(20,'vs4','v','','present tense plural (are)',NULL,NULL);
INSERT INTO poses VALUES(47,'we','we','wordpart','multi-word ending',NULL,NULL);
INSERT INTO poses VALUES(49,'wep','we','wordpart','possessive',NULL,NULL);
INSERT INTO poses VALUES(50,'weps','we','wordpart','plural possessive',NULL,NULL);
INSERT INTO poses VALUES(48,'wes','we','wordpart','plural',NULL,NULL);
INSERT INTO poses VALUES(46,'wp','wp','wordpart','multi-word part',NULL,NULL);
INSERT INTO poses VALUES(51,'x','x','nonword','non word',NULL,'for example a roman numeral');
INSERT INTO base_poses VALUES(1,'','?','','unknown',NULL);
INSERT INTO base_poses VALUES(9,'a','a0','','adjective/adverb',NULL);
INSERT INTO base_poses VALUES(15,'abbr','abbr','special','abbreviation',NULL);
INSERT INTO base_poses VALUES(7,'aj','aj0','','adjective',NULL);
INSERT INTO base_poses VALUES(3,'aj_av','a0','','adjective and adverb',NULL);
INSERT INTO base_poses VALUES(8,'av','av0','','adverb',NULL);
INSERT INTO base_poses VALUES(11,'c','c','','conjunction',NULL);
INSERT INTO base_poses VALUES(13,'d','d','','determiner',NULL);
INSERT INTO base_poses VALUES(14,'i','i','','interjection',NULL);
INSERT INTO base_poses VALUES(6,'m','m0','','noun/verb',NULL);
INSERT INTO base_poses VALUES(4,'n','n0','','noun',NULL);
INSERT INTO base_poses VALUES(2,'n_v','m0','','noun and verb',NULL);
INSERT INTO base_poses VALUES(10,'pn','pn0','','pronoun',NULL);
INSERT INTO base_poses VALUES(12,'pp','pp','','preposition',NULL);
INSERT INTO base_poses VALUES(17,'pre','pre','nonword','prefix',NULL);
INSERT INTO base_poses VALUES(16,'s','s','special','contraction',NULL);
INSERT INTO base_poses VALUES(18,'suf','suf','nonword','suffix',NULL);
INSERT INTO base_poses VALUES(5,'v','v0','','verb',NULL);
INSERT INTO base_poses VALUES(20,'we','we','wordpart','multi-word ending',NULL);
INSERT INTO base_poses VALUES(19,'wp','wp','wordpart','multi-word part',NULL);
INSERT INTO base_poses VALUES(21,'x','x','nonword','non word','for example a roman numeral');
INSERT INTO ranks VALUES(1,'','');
INSERT INTO ranks VALUES(6,'!','infrequent');
INSERT INTO ranks VALUES(2,'*','usage dependent');
INSERT INTO ranks VALUES(3,'-','uncommon');
INSERT INTO ranks VALUES(4,'@','archaic');
INSERT INTO ranks VALUES(5,'~','inapplicable');
INSERT INTO variant_levels VALUES(0,'','',0);
INSERT INTO variant_levels VALUES(1,'.','include',0);
INSERT INTO variant_levels VALUES(2,'=','equal',1);
INSERT INTO variant_levels VALUES(3,'?','disagreement',1);
INSERT INTO variant_levels VALUES(4,'v','common',1);
INSERT INTO variant_levels VALUES(5,'~','variant',2);
INSERT INTO variant_levels VALUES(6,'V','acceptable',2);
INSERT INTO variant_levels VALUES(7,'-','uncommon',3);
INSERT INTO variant_levels VALUES(8,'@','archaic',3);
INSERT INTO variant_levels VALUES(9,'x','invalid',4);
INSERT INTO regions VALUES(1,'',NULL);
INSERT INTO regions VALUES(5,'AU',NULL);
INSERT INTO regions VALUES(4,'CA',NULL);
INSERT INTO regions VALUES(3,'GB',NULL);
INSERT INTO regions VALUES(2,'US',NULL);
INSERT INTO spellings VALUES(2,'A','US','American');
INSERT INTO spellings VALUES(3,'B','GB','British(ise)');
INSERT INTO spellings VALUES(5,'C','CA','Canadian');
INSERT INTO spellings VALUES(6,'D','AU','Australian');
INSERT INTO spellings VALUES(4,'Z','GB','British(ize)');
INSERT INTO spellings VALUES(1,'_','','');
END;
